### ISSUE TITLE
User upload Button 

### ISSUE THREAD

**Issue by Akeldamaa** [Akeldamaa/Cat-A-Log#1]
Create a button on the "Scan Your Cat" section that allows users to upload a photo of their cat.

**Comment by Akeldamaa** [comment]
User Upload Button

  Description: Implement a button that allows users to upload a photo of their cat.
    Priority: High
    Labels: Feature, Frontend
    Assignees: Jayden 
    Tasks:
        Create a UI component for the upload button.
        Validate the file type (image) and size before uploading.
        Ensure the button is accessible and easy to use.

**Comment by JaydenPearlM** [comment]
> User Upload Button
> 
> Description: Implement a button that allows users to upload a photo of their cat. Priority: High Labels: Feature, Frontend Assignees: Jayden Tasks: Create a UI component for the upload button. Validate the file type (image) and size before uploading. Ensure the button is accessible and easy to use.

On it!

**Comment by Moyinoluwa-10** [comment]
Done
