### ISSUE TITLE
Display Scanning Progress

### ISSUE THREAD

**Issue by Akeldamaa** [Akeldamaa/Cat-A-Log#3]
Add a progress indicator that shows the status of the image scanning process.

**Comment by Akeldamaa** [comment]
display Scanning Progress

    Description: Display the progress of scanning the uploaded photo.
    Priority: Medium
    Labels: Feature, Frontend
    Tasks:
        Implement a progress bar or indicator.
        Update the progress based on the backend processing status.

**Comment by EmeraldVoltron** [comment]
completed, progress bar component.
